version: 2
jobs:
  build:
    docker:
      - image: jacekelgda/pr-troll:123asd123asd123
    working_directory: ~/my-app
    steps:
      - checkout
      - run: pwd
      - run: ls -ali
      - run: git log
      - run: pr-troll
